[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.13"

[profile.default.rpc_endpoints]
fork_url = "${FORK_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config