name: test

on: [pull_request]

jobs:
  check:
    strategy:
      fail-fast: true

    name: Merkle Order Settlement tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge tests
        run: FORK_URL="https://mainnet.infura.io/v3/7bb117a7f3ad464292087467a7c93fb8" forge test -vvv
